packages:
  - "packages/*"
  - "examples/*"

# This is a catalog of dependencies that are shared across the project.
# We need to keep up to date with our workers env from cloudflare here https://github.com/cloudflare/workers-sdk/blob/main/pnpm-workspace.yaml

catalog:
  "@types/node": "^20.19.9"
  "@typescript-eslint/eslint-plugin": "^8.35.1"
  "@typescript-eslint/parser": "^8.35.1"
  "@vitest/runner": ~3.2.0
  "@vitest/snapshot": ~3.2.0
  "@vitest/ui": ~3.2.0
  # rimraf@6 requires node 20 or >=22
  rimraf: "^6.0.1"
  typescript: "^5.8.3"
  undici: "^7.10.0"
  vitest: "~3.2.0"
  vite: "^5.4.14"
  "ws": "8.18.0"
  esbuild: "0.25.4"
  playwright-chromium: "^1.49.1"
  "@cloudflare/workers-types": "^4.20250823.0"
  "@cloudflare/vitest-pool-workers": "0.8.66"
  wrangler: "^4.32.0"
  workerd: "1.20250823.0"
  "@modelcontextprotocol/sdk": "^1.17.4"
