/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 6def92d1e5580c943393e2fcdb68c642)
declare namespace Cloudflare {
	interface Env {
		TODO_MCP_SERVER: DurableObjectNamespace<import("./src/index").TodoMcpServer>;
	}
}
interface Env extends Cloudflare.Env {}
