/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false`
declare namespace Cloudflare {
	interface Env {
		EXPENSE_MCP_SERVER: DurableObjectNamespace<import("./src/index").ExpenseMcpServer>;
	}
}

interface Env extends Cloudflare.Env {}

// Type definitions for Cloudflare Workers test environment
declare module 'cloudflare:test' {
  export interface ExecutionContext {
    waitUntil(promise: Promise<any>): void;
    passThroughOnException(): void;
  }
  
  export function createExecutionContext(): ExecutionContext;
  export function waitOnExecutionContext(ctx: ExecutionContext): Promise<void>;
  export const env: any;
} 