// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 4153dcdeb3dfa147b95fbd9a1e308f20)
declare namespace Cloudflare {
	interface Env {}
}
interface Env extends Cloudflare.Env {}
